_ContentsGroup_3DMiniMapOpen = ToClient_IsContentsGroupOpen("345")
_ContentsGroup_isFurnitureWarehouse = ToClient_IsContentsGroupOpen("342")
_ContentsGroup_isUsedNewEnchant = true
_ContentsGroup_isUsedNewTradeEventNotice = true
_ContentsGroup_isMemoOpen = true
_ContentsGroup_isNewLifeRanking = true
_ContentsGroup_isNewOption = true
_ContentsGroup_skillOldandNew = ToClient_IsContentsGroupOpen("920")
_ContentsGroup_isUsedNewCharacterInfo = true
_ContentsGroup_webAlbumOpen = ToClient_IsContentsGroupOpen("205")
_ContentsGroup_isContentsCustomizationVoice = ToClient_IsContentsGroupOpen("244")
_ContentsGroup_isConsoleTest = ToClient_IsDevelopment() or ToClient_isXBox()
_ContentsGroup_isCamp = ToClient_IsContentsGroupOpen("347")
_ContentsGroup_isFairy = ToClient_IsContentsGroupOpen("357")
_ContentsGroup_isAllWarehouse = ToClient_IsContentsGroupOpen("366")
_ContentsGroup_isSecretExtract = ToClient_IsContentsGroupOpen("247")
